version: "3"
services:
  jjalapp:
    build: ./
    restart: always
    volumes:
      - ./image:/usr/src/app/image
      - ./sqlite.db:/usr/src/app/sqlite.db
networks:
  default:
    external:
      name: external-network